name: Build Java WAR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone source code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: Upload WAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: demo-war
        path: target/demo.war
